@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "Main#main(String[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": false,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": true,
    "showMethodParametersNames": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showCallOrder": true,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": true
  },
  "rootClass": "Main",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_21388906 { 
   	label=RealTicket
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1012934546 { 
   	label=RealTicket
	labeljust=l
	fillcolor=white
	style=filled
   
   RealTicket21388906XXXRealTicket0[
	label="+ RealTicket()"
	style=filled
	fillcolor=white
	tooltip="RealTicket

null"
	fontcolor=darkgreen
];

RealTicket21388906XXXgetInfo0[
	label="+ getInfo()"
	style=filled
	fillcolor=white
	tooltip="RealTicket

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_2390489 { 
   	label=Main
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1706522830 { 
   	label=Main
	labeljust=l
	fillcolor=white
	style=filled
   
   Main2390489XXXmain1859653459[
	label="+ main(args: String[])"
	style=filled
	fillcolor=white
	tooltip="Main

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_511394054 { 
   	label=ProxyTicket
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_700222982 { 
   	label=ProxyTicket
	labeljust=l
	fillcolor=white
	style=filled
   
   ProxyTicket511394054XXXProxyTicket1808118735[
	label="+ ProxyTicket(userRole: String)"
	style=filled
	fillcolor=white
	tooltip="ProxyTicket

null"
	fontcolor=darkgreen
];

ProxyTicket511394054XXXgetInfo0[
	label="+ getInfo()"
	style=filled
	fillcolor=white
	tooltip="ProxyTicket

null"
	fontcolor=darkgreen
];
} 
} 

'edges    
Main2390489XXXmain1859653459 -> ProxyTicket511394054XXXProxyTicket1808118735[label=0];
Main2390489XXXmain1859653459 -> ProxyTicket511394054XXXProxyTicket1808118735[label=3];
Main2390489XXXmain1859653459 -> ProxyTicket511394054XXXgetInfo0;
Main2390489XXXmain1859653459 -> RealTicket21388906XXXgetInfo0;
ProxyTicket511394054XXXgetInfo0 -> RealTicket21388906XXXRealTicket0[label=3];
ProxyTicket511394054XXXgetInfo0 -> RealTicket21388906XXXgetInfo0[label=5];
    
}
@enduml